server:
  port: 9092
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/smallProgram?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms
    port: 6379
    host: apptest.pzfresh.com
    password: Pzfresh2019

mybatis:
  mapper-locations: classpath*:com/fty/mapper/*.xml
  type-aliases-package: com.fty.entity
  type-handlers-package: com.fty.typeHandler
logging:
  level:
    root: warn
    org.springframework.web: warn
    org.mybatis: debug
