/*
 * This file is generated by jOOQ.
 */
package com.fty.jooq.domain;


import com.fty.jooq.domain.tables.MallClass;
import com.fty.jooq.domain.tables.MallUser;
import com.fty.jooq.domain.tables.TUser;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>smallprogram</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<Record, Integer> IDENTITY_T_USER = Identities0.IDENTITY_T_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> KEY_MALL_CLASS_PRIMARY = UniqueKeys0.KEY_MALL_CLASS_PRIMARY;
    public static final UniqueKey<Record> KEY_MALL_USER_PRIMARY = UniqueKeys0.KEY_MALL_USER_PRIMARY;
    public static final UniqueKey<Record> KEY_T_USER_PRIMARY = UniqueKeys0.KEY_T_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<Record, Integer> IDENTITY_T_USER = Internal.createIdentity(TUser.T_USER, TUser.T_USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<Record> KEY_MALL_CLASS_PRIMARY = Internal.createUniqueKey(MallClass.MALL_CLASS, "KEY_mall_class_PRIMARY", MallClass.MALL_CLASS.CLASS_ID);
        public static final UniqueKey<Record> KEY_MALL_USER_PRIMARY = Internal.createUniqueKey(MallUser.MALL_USER, "KEY_mall_user_PRIMARY", MallUser.MALL_USER.USER_ID);
        public static final UniqueKey<Record> KEY_T_USER_PRIMARY = Internal.createUniqueKey(TUser.T_USER, "KEY_t_user_PRIMARY", TUser.T_USER.ID);
    }
}
