/*
 * This file is generated by jOOQ.
 */
package com.fty.jooq.domain;


import com.fty.jooq.domain.tables.MallClass;
import com.fty.jooq.domain.tables.MallUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Smallprogram extends SchemaImpl {

    private static final long serialVersionUID = 1755043245;

    /**
     * The reference instance of <code>smallprogram</code>
     */
    public static final Smallprogram SMALLPROGRAM = new Smallprogram();

    /**
     * The table <code>smallprogram.mall_class</code>.
     */
    public final MallClass MALL_CLASS = com.fty.jooq.domain.tables.MallClass.MALL_CLASS;

    /**
     * The table <code>smallprogram.mall_user</code>.
     */
    public final MallUser MALL_USER = com.fty.jooq.domain.tables.MallUser.MALL_USER;

    /**
     * No further instances allowed
     */
    private Smallprogram() {
        super("smallprogram", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            MallClass.MALL_CLASS,
            MallUser.MALL_USER);
    }
}
