/*
 * This file is generated by jOOQ.
 */
package com.fty.jooq.domain;


import com.fty.jooq.domain.tables.MallClass;
import com.fty.jooq.domain.tables.MallUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in smallprogram
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>smallprogram.mall_class</code>.
     */
    public static final MallClass MALL_CLASS = com.fty.jooq.domain.tables.MallClass.MALL_CLASS;

    /**
     * The table <code>smallprogram.mall_user</code>.
     */
    public static final MallUser MALL_USER = com.fty.jooq.domain.tables.MallUser.MALL_USER;
}
