/*
 * This file is generated by jOOQ.
 */
package com.fty.jooq.domain.tables;


import com.fty.jooq.domain.Indexes;
import com.fty.jooq.domain.Keys;
import com.fty.jooq.domain.Smallprogram;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MallClass extends TableImpl<Record> {

    private static final long serialVersionUID = -1955778303;

    /**
     * The reference instance of <code>smallprogram.mall_class</code>
     */
    public static final MallClass MALL_CLASS = new MallClass();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>smallprogram.mall_class.class_id</code>.
     */
    public final TableField<Record, Integer> CLASS_ID = createField("class_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>smallprogram.mall_class.class_code</code>.
     */
    public final TableField<Record, String> CLASS_CODE = createField("class_code", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>smallprogram.mall_class.class_name</code>.
     */
    public final TableField<Record, String> CLASS_NAME = createField("class_name", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>smallprogram.mall_class.class_pid</code>.
     */
    public final TableField<Record, Integer> CLASS_PID = createField("class_pid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>smallprogram.mall_class.img_url</code>.
     */
    public final TableField<Record, String> IMG_URL = createField("img_url", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>smallprogram.mall_class.class_level</code>.
     */
    public final TableField<Record, Integer> CLASS_LEVEL = createField("class_level", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>smallprogram.mall_class</code> table reference
     */
    public MallClass() {
        this(DSL.name("mall_class"), null);
    }

    /**
     * Create an aliased <code>smallprogram.mall_class</code> table reference
     */
    public MallClass(String alias) {
        this(DSL.name(alias), MALL_CLASS);
    }

    /**
     * Create an aliased <code>smallprogram.mall_class</code> table reference
     */
    public MallClass(Name alias) {
        this(alias, MALL_CLASS);
    }

    private MallClass(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private MallClass(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> MallClass(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, MALL_CLASS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Smallprogram.SMALLPROGRAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MALL_CLASS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_MALL_CLASS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_MALL_CLASS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallClass as(String alias) {
        return new MallClass(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallClass as(Name alias) {
        return new MallClass(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MallClass rename(String name) {
        return new MallClass(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MallClass rename(Name name) {
        return new MallClass(name, null);
    }
}
